=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer1/ej1_xsd/novedades.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="novedades" type="tipoNovedades" />
    <xsd:complexType name="tipoNovedades">
        <xsd:sequence>
            <xsd:element name="fecha" type="xsd:string" />
            <xsd:choice minOccurs="1" maxOccurs="unbounded">
                <xsd:element name="libro" type="tipoLibro" />
                <xsd:element name="disco" type="tipoDisco" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tipoDisco">
        <xsd:sequence>
            <xsd:element name="titulo" type="xsd:string" />
            <xsd:element name="interprete" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="direccion" minOccurs="0" type="xsd:anyURI" />
        </xsd:sequence>
        <xsd:attribute name="genero" type="generoMusical" use="required" />
    </xsd:complexType>
    <xsd:complexType name="tipoLibro">
        <xsd:sequence>
            <xsd:element name="titulo" type="xsd:string" />
            <xsd:element name="autor" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
            <xsd:element name="direccion" minOccurs="0"  type="xsd:anyURI" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="generoMusical">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="rock" />
            <xsd:enumeration value="pop" />
            <xsd:enumeration value="clasica" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer1/ej1_xsd/novedades.xml
<?xml version="1.0"  standalone="no"?>
<novedades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="novedades.xsd">

    <fecha>Octubre 2000</fecha>
    <disco genero="pop">
        <titulo>O sea</titulo>
        <interprete>Enrique Iglesias</interprete>
    </disco>
    <libro>
        <titulo>Aplicaciones web</titulo>
        <autor>John McCarra</autor>
        <autor>Frank Webini</autor>
    </libro>

</novedades>
