=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer3/ejer3_xsd/programming_library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="programming_library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="language" minOccurs="3" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="creator" type="xs:string" />
                            <xs:element name="year_created" type="xs:integer" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="day_created" type="xs:integer" />
                        </xs:sequence>
                        <xs:attribute name="dificultad" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="sencillo" />
                                    <xs:enumeration value="intermedio" />
                                    <xs:enumeration value="avanzado" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="velocidad" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="lento" />
                                    <xs:enumeration value="moderado" />
                                    <xs:enumeration value="rapido" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="popularidad" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="poca" />
                                    <xs:enumeration value="media" />
                                    <xs:enumeration value="mucha" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="trending" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="alto" />
                                    <xs:enumeration value="medio" />
                                    <xs:enumeration value="bajo" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer3/ejer3_xsd/programming_library.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<programming_library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="programming_library.xsd">
    <language dificultad="sencillo" trending="alto">
        <name>Python</name>
        <creator>Guido van Rossum</creator>
        <year_created>1991</year_created>
        <description>Lenguaje de programación interpretado y de alto nivel.</description>
        <day_created>11</day_created>
    </language>

    <language dificultad="sencillo">
        <name>Java</name>
        <creator>James Gosling</creator>
        <year_created>1995</year_created>
        <description>Lenguaje orientado a objetos</description>
        <day_created>11</day_created>
    </language>
    
    <language dificultad="sencillo">
        <name>JavaScript</name>
        <creator>Brendan Eich</creator>
        <year_created>1995</year_created>
        <description>Lenguaje de programación interpretado, dialecto del estándar ECMAScript.</description>
        <day_created>11</day_created>
    </language>

</programming_library>
