=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer1/ej1_dtd/novedades.dtd
<!ELEMENT novedades (fecha,(disco|libro)*)>
<!ELEMENT fecha (#PCDATA)>

<!ELEMENT disco (titulo,interprete,direccion?)>
<!ATTLIST disco genero (rock|pop|melodica|clasica|dance) #REQUIRED >
<!ELEMENT libro (titulo, autor+,direccion?)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT interprete (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer1/ej1_dtd/novedades.xml
<?xml version="1.0"  standalone="no"?>
<!DOCTYPE novedades SYSTEM "novedades.dtd">

<novedades>
    <fecha>Octubre 2000</fecha>
    <disco genero="pop">
        <titulo>O sea</titulo>
        <interprete>Enrique Iglesias</interprete>
    </disco>
    <libro>
        <titulo>Aplicaciones web</titulo>
        <autor>John McCarra</autor>
        <autor>Frank Webini</autor>
    </libro>

</novedades>
