=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer3/ejer3_dtd/programming_library.dtd
<!ELEMENT programming_library (language,language, language+)>
<!ELEMENT language (name, creator, year_created, description, day_created)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT year_created (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT day_created (#PCDATA)>

<!ATTLIST language dificultad (sencillo | intermedio | avanzado) #REQUIRED>
<!ATTLIST language velocidad (lento | moderado | rapido) #IMPLIED>
<!ATTLIST language popularidad (poca | media | mucha) #IMPLIED>
<!ATTLIST language trending (bajo | medio | alto) #IMPLIED>

=== JavierCresp0/tecnologias-web/01-XML-DTD-XSD/ejer3/ejer3_dtd/programming_library.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE programming_library SYSTEM "programming_library.dtd">
<programming_library>  
    <language dificultad="sencillo" trending="alto">
        <name>Python</name>
        <creator>Guido van Rossum</creator>
        <year_created>1991</year_created>
        <description>Lenguaje de programación interpretado y de alto nivel.</description>
        <day_created>11</day_created>
    </language>

    <language dificultad="sencillo">
        <name>Java</name>
        <creator>James Gosling</creator>
        <year_created>1995</year_created>
        <description>Lenguaje orientado a objetos</description>
        <day_created>11</day_created>
    </language>
    
    <language dificultad="sencillo" >
        <name>JavaScript</name>
        <creator>Brendan Eich</creator>
        <year_created>1995</year_created>
        <description>Lenguaje de programación interpretado, dialecto del estándar ECMAScript.</description>
        <day_created>11</day_created>
    </language>    
</programming_library>
